<?php
use angelrove\membrillo2\WApp\Local;

Local::$t['delete'] = 'Delete';
Local::$t['new']    = 'New';
Local::$t['accept'] = 'Accept';
Local::$t['save']   = 'Save';
Local::$t['save_and_new'] = 'Insert other &raquo;';
Local::$t['close']  = 'Close';
Local::$t['view']   = 'View';
Local::$t['Search'] = 'Search';
Local::$t['close_session'] = 'Close session';
Local::$t['WList_del_m'] = "Va a eliminar el registro. Are you sure?";
Local::$t['GenQuery_error_obliga'] = 'campo obligatorio';
Local::$t['GenQuery_error_unique'] = 'está siendo utilizado';

// Paginacion ---
Local::$t['to'] = 'to';
Local::$t['of'] = 'of';
