<?php
use angelrove\membrillo\WApp\Local;

// My account
Local::$t['My account'] = 'My account';
Local::$t['My data'] = 'My data';
Local::$t['Change password'] = 'Change password';
Local::$t['Logout'] = 'Logout';
Local::$t['New password'] = 'New password';

//-----------
Local::$t['delete'] = 'Delete';
Local::$t['new']    = 'New';
Local::$t['accept'] = 'Accept';
Local::$t['save']   = 'Save';
Local::$t['save_continue'] = 'Save and continue';
Local::$t['save_and_new']  = 'Insert other &raquo;';
Local::$t['close']  = 'Cancel';
Local::$t['view']   = 'View';
Local::$t['Search'] = 'Search';
Local::$t['close_session'] = 'Close session';
Local::$t['WList_del_m'] = "Va a eliminar el registro. Are you sure?";
Local::$t['GenQuery_error_obliga'] = 'campo obligatorio';
Local::$t['GenQuery_error_unique'] = 'está siendo utilizado';

Local::$t['Saved'] = 'Saved!';

// Paginacion ---
Local::$t['Showing'] = 'Showing';
Local::$t['to'] = 'to';
Local::$t['of'] = 'of';

// Login ---
Local::$t['Username'] = 'Username';
Local::$t['Password'] = 'Password';
