<?php
use angelrove\membrillo2\WApp\Local;

Local::$t['delete'] = 'Eliminar';
Local::$t['new']    = 'Nuevo';
Local::$t['accept'] = 'Aceptar';
Local::$t['save']   = 'Guardar';
Local::$t['save_and_new'] = 'Insertar otro &raquo;';
Local::$t['close']  = 'Cerrar';
Local::$t['view']   = 'Ver';
Local::$t['Search'] = 'Buscar';
Local::$t['close_session'] = 'Cerrar sesión';
Local::$t['WList_del_m'] = "Va a eliminar el registro. ¿Está seguro?";
Local::$t['GenQuery_error_obliga'] = 'campo obligatorio';
Local::$t['GenQuery_error_unique'] = 'está siendo utilizado';

// Paginacion ---
Local::$t['to'] = 'a';
Local::$t['of'] = 'de';
