<?
self::$lang = array
(
   'delete' => 'Delete',
   'new'    => 'New',
   'accept' => 'Accept',
   'save'   => 'Save',
   'save_and_new' => 'Insert other &raquo;',
   'close'  => 'Close',
   'view'   => 'View',
   'close_session' => 'Close session',

   'WList_del_m' => "Va a eliminar el registro. Are you sure?",
   'GenQuery_error_obliga' => 'campo obligatorio',
   'GenQuery_error_unique' => 'está siendo utilizado',
);
